"""Select and initialize the host state shared by asys commands."""
import grp
import os
from pathlib import Path
import re
import shlex
import subprocess
import tempfile


def state_root(section=None):
    base = Path(os.environ.get('ASYS_STATE_ROOT') or
                Path(os.environ.get('XDG_STATE_HOME') or Path.home() / '.local/state') / 'asys').expanduser()
    return base / section if section else base


def group_id(name):
    if name is None:
        return None
    try:
        gid = grp.getgrnam(name).gr_gid
    except KeyError:
        raise ValueError(f'Unknown group: {name}') from None
    if os.geteuid() != 0 and gid not in [os.getegid(), *os.getgroups()]:
        raise ValueError(f'Current user is not a member of group {name}')
    return gid


def initialize(args):
    root = args.directory.expanduser().resolve()
    gid = group_id(args.group)
    dcomp = (args.dcomp or Path(os.environ.get('DCOMP_STATE_ROOT') or
             Path(os.environ.get('XDG_STATE_HOME') or Path.home() / '.local/state') / 'dcomp')).expanduser().resolve()
    script = root / 'asys-env'
    header = '# Generated by asys init\n'
    if script.is_symlink() or script.exists() and not script.read_text().startswith(header):
        raise ValueError(f'{script} already exists and was not generated by asys init')
    if root.exists() and any(root.iterdir()):
        info = root.stat()
        if gid is not None and (info.st_gid != gid or info.st_mode & 0o2070 != 0o2070):
            raise ValueError(f'{root} is already initialized with different permissions')
    else:
        missing = []
        parent = root
        while gid is not None and not parent.exists():
            missing.append(parent)
            parent = parent.parent
        root.mkdir(parents=True, exist_ok=True, mode=0o700)
        if gid is not None:
            for path in reversed(missing):
                os.chown(path, -1, gid)
                path.chmod(0o2770)
            os.chown(root, -1, gid)
        root.chmod(0o2770 if gid is not None else 0o700)
    shared = root.stat().st_mode & 0o2070 == 0o2070
    for name in ('runs', 'inference', 'human'):
        path = root / name
        try:
            path.mkdir(mode=0o700)
        except FileExistsError:
            if not path.is_dir():
                raise ValueError(f'{path} is not a directory') from None
        else:
            path.chmod(0o2770 if shared else 0o700)
    if args.dcomp is not None:
        command = [os.environ.get('DCOMP_BINARY') or 'dcomp', 'init', str(dcomp)]
        if args.group:
            command += ['--group', args.group]
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode:
            raise ValueError(result.stderr.strip() or 'dcomp initialization failed')
    exports = f'export DCOMP_STATE_ROOT={shlex.quote(str(dcomp))}\nexport ASYS_STATE_ROOT={shlex.quote(str(root))}\n'
    # Prompt text is literal: a directory name must not introduce shell or
    # terminal prompt escapes. Keep the original prompt when switching setups.
    name = re.sub(r'[^A-Za-z0-9 ._-]', '_', root.name) or 'asys'
    prompt = (
        '\nif [ "${PS1+x}" = x ]; then\n'
        '    if [ "${_ASYS_BASE_PS1+x}" != x ]; then _ASYS_BASE_PS1=$PS1; fi\n'
        f'    PS1={shlex.quote("{ " + name + " } ")}"$_ASYS_BASE_PS1"\n'
        'fi\n'
    )
    with tempfile.NamedTemporaryFile(mode='w', dir=script.parent, prefix='.asys-env-', delete=False) as output:
        temporary = Path(output.name)
        try:
            output.write(header + exports + prompt)
            output.flush()
            os.fsync(output.fileno())
            os.fchmod(output.fileno(), 0o660 if shared else 0o600)
            temporary.replace(script)
        finally:
            temporary.unlink(missing_ok=True)
    print(exports, end='')
    print(f'\nTo use this setup in this shell:\n  source {shlex.quote(str(script))}')
